### ISSUE TITLE
CVE5.0 it is bad pratice to hard code version numbers into tags...

### ISSUE THREAD

**Issue by MrSeccubus** [Vulnogram/Vulnogram#64]
CVSS record forat is:
```
        {
          "format": "CVSS",
          "scenarios": [
            {
              "lang": "en",
              "value": "GENERAL"
            }
          ],
          "cvssV3_1": {
            "version": "3.1",
            "attackVector": "NETWORK",
            "attackComplexity": "LOW",
            "privilegesRequired": "LOW",
            "userInteraction": "NONE",
            "scope": "CHANGED",
            "confidentialityImpact": "LOW",
            "integrityImpact": "HIGH",
            "availabilityImpact": "NONE",
            "baseScore": 8.5,
            "baseSeverity": "HIGH",
            "vectorString": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:C/C:L/I:H/A:N"
          }
        },
```

This means that when the CVSS version changes to e.g. v3.2 the tag changes as well, meaning I have to update the code that renders CVEs records on https:csirt.divd.nl.

Having a version number as part of a tag is generally considered bad practice.

Is this is not the correct place to discuss this, should I discuss it elsewhere?

**Comment by chandanbn** [comment]
By "tags" if you meant the JSON key (eg. "cvssV3_1", "cvssV2_0", ..) I completely agree, and I argued against this format while JSON schema was being designed. IMHO it should be something "cvss" - thats it.
The version is anyway captured in the "version" field's value as "3.1", but I lost the argument.
IIRC mainly because when someone wants to provide both CVSS v2 and V3 scores at the same time, so the version numbers were hard coded in the field names.

If you think it is import to change this please raise this on the schema project https://github.com/CVEProject/cve-schema.

**Comment by MrSeccubus** [comment]
Rasied at: https://github.com/CVEProject/cve-schema/issues/163
