### ISSUE TITLE
clearly distinguish between CVE info and advisory info

### ISSUE THREAD

**Issue by tomturner-citrix** [Vulnogram/Vulnogram#84]
As Vulnogram is to become the official online tool for CNAs to publish CVEs, it would be very useful if users of the 'editor' could easily distinguish between info that's used to generate a CVE JSON file and info used for the advisory feature. Many vendors will have their own advisory publishing mechanisms and will only be using vulnogram to generate the CVE JSON

**Comment by chandanbn** [comment]
With CVE JSON 5.0 and [Vulnogram 0.1.0](https://vulnogram.github.io/cve5/#editor) the only extra fields are: bug ids, advisory ids, source of discovery, and a fields that Vulnogram version used for generating the record. These are optional. The generated [advisory](https://vulnogram.github.io/cve5/#advisory) is a byproduct of creating a CVE JSON record, mostly uses the data from the CVE JSON.

Vulnogram by default shows some commonly useful but optional fields such as problem types, impacts and CVSS scores. Since the CVE program is moving towards a more self-service model, one can easily fill in "blah blah" for a CVE description and publish it. Three or four of these optional structured fields can help auto generate the CVE description itself. These provide guide-rails against someone posting a vague CVE description that doesn't help uniquely identify the vulnerability.

**Comment by tomturner-citrix** [comment]
Many thanks Chandan for your quick response,
Appreciate that some of these optional features may be useful for some folk. We just think it would be really useful if it was clearer when an optional field doesnt affect the CVE record

**Comment by chandanbn** [comment]
The required fields have bold labels and a red asterisk and are towards the top of the page. Optional fields are in the later half. There is some investigation into "just the basic minimum to get a CVE published" view see #91  and https://democert.org/vulnogram/
